import Foundation

/// ルート `TabView` の選択（ホーム／書庫／設定）。
enum AppRootTab: Hashable {
    case home
    case library
    case settings
}

/// Stable identifiers for foundation branches (not UI-specific).
enum BranchIdentifier {
    static let scpJapan = "scp-jp"
    static let scpWikiEN = "scp-wiki-en"
    static let scpInternational = "scp-int"
}

/// Keys for `Localizable.strings` (keep in sync with `en.lproj` / `ja.lproj`).
enum LocalizationKey {
    static let homeTitle = "home.title"
    static let branchBaseURLLabel = "home.branch_url_label"

    static let categorySiteTop = "category.site_top"
    static let categorySeriesJP1 = "category.series_jp_1"
    static let categorySeriesJP2 = "category.series_jp_2"
    static let categorySeriesJP3 = "category.series_jp_3"
    static let categorySeriesJP4 = "category.series_jp_4"
    static let categoryTalesJP = "category.tales_jp"
    static let categoryCredits = "category.credits"

    static let categoryENSiteTop = "category.en.site_top"
    static let categoryENSeries1 = "category.en.series_1"
    static let categoryENSeries2 = "category.en.series_2"
    static let categoryENSeries3 = "category.en.series_3"
    static let categoryENSeries4 = "category.en.series_4"
    static let categoryENSeries5 = "category.en.series_5"
    static let categoryENTales = "category.en.tales"
    static let categoryENLicensing = "category.en.licensing"

    static let categoryINTSiteTop = "category.int.site_top"
    static let categoryINTBranches = "category.int.branches"
    static let categoryINTRules = "category.int.rules"
    static let categoryINTTagGuide = "category.int.tag_guide"
    static let categoryINTChat = "category.int.chat"

    static let tabHome = "tab.home"
    static let tabLibrary = "tab.library"
    static let tabSettings = "tab.settings"

    static let settingsTitle = "settings.title"
    static let settingsSectionBranch = "settings.section.branch"
    static let settingsBranchPicker = "settings.branch_picker"
    static let settingsSectionLocaleReader = "settings.section.locale_reader"
    static let settingsUILanguagePicker = "settings.ui_language.picker"
    static let settingsUILanguageSystem = "settings.ui_language.system"
    static let settingsUILanguageJapanese = "settings.ui_language.japanese"
    static let settingsUILanguageEnglish = "settings.ui_language.english"
    static let settingsReaderFontSize = "settings.reader.font_size"
    static let settingsReaderFontSizeFooter = "settings.reader.font_size.footer"
    static let settingsSectionData = "settings.section.data"
    static let settingsClearHistory = "settings.clear_history"
    static let settingsClearBookmarks = "settings.clear_bookmarks"
    static let settingsClearWebCache = "settings.clear_web_cache"
    static let settingsWebCacheCleared = "settings.web_cache_cleared"
    static let settingsSectionAbout = "settings.section.about"
    static let settingsAppVersion = "settings.app_version"
    static let settingsLicenseCreditTitle = "settings.license.title"
    static let settingsLicenseCreditBody = "settings.license.body"
    static let settingsLicenseLinkTitle = "settings.license.link"
    static let settingsConfirmTitle = "settings.confirm.title"
    static let settingsConfirmDelete = "settings.confirm.delete"
    static let settingsConfirmCancel = "settings.confirm.cancel"
    static let settingsConfirmHistoryMessage = "settings.confirm.history_message"
    static let settingsConfirmBookmarksMessage = "settings.confirm.bookmarks_message"
    static let libraryTitle = "library.title"
    static let librarySegmentBookmarks = "library.segment.bookmarks"
    static let librarySegmentHistory = "library.segment.history"
    static let libraryEmptyBookmarksTitle = "library.empty.bookmarks.title"
    static let libraryEmptyBookmarksDescription = "library.empty.bookmarks.description"
    static let libraryEmptyHistoryTitle = "library.empty.history.title"
    static let libraryEmptyHistoryDescription = "library.empty.history.description"
    static let searchJumpToSCP = "home.search.jump_scp"

    static let homeSectionArchiveTitle = "home.section.archive.title"
    static let homeSectionArchiveSubtitle = "home.section.archive.subtitle"
    static let homeSectionScpLibraryTitle = "home.section.scp_library.title"
    static let homeSectionScpLibrarySubtitle = "home.section.scp_library.subtitle"
    static let homeSectionInternationalTitle = "home.section.international.title"
    static let homeSectionInternationalSubtitle = "home.section.international.subtitle"
    static let homeSectionGoIPersonnelTitle = "home.section.goi_personnel.title"
    static let homeSectionGoIPersonnelSubtitle = "home.section.goi_personnel.subtitle"
    static let homeSectionGuideTitle = "home.section.guide.title"
    static let homeSectionGuideSubtitle = "home.section.guide.subtitle"
    static let homeSectionEventsTitle = "home.section.events.title"
    static let homeSectionEventsSubtitle = "home.section.events.subtitle"

    static let goiPortalTitle = "goi.portal.title"
    static let goiPortalNativeListTitle = "goi.portal.native_list.title"
    static let goiPortalNativeListSubtitle = "goi.portal.native_list.subtitle"
    static let goiPortalPersonnelTitle = "goi.portal.personnel.title"
    static let goiPortalPersonnelSubtitle = "goi.portal.personnel.subtitle"

    static let libraryCategoryGoITitle = "library.category.goi.title"
    static let libraryCategoryGoISubtitle = "library.category.goi.subtitle"
    static let libraryItemGoIHubMasterEN = "library.item.goi_hub_master_en"

    static let settingsSectionMonetization = "settings.section.monetization"
    static let settingsPurchaseRemoveAds = "settings.purchase.remove_ads"
    static let settingsPurchaseRestore = "settings.purchase.restore"
    static let settingsPurchaseBusy = "settings.purchase.busy"
    static let settingsPurchaseAdFreeActive = "settings.purchase.adfree_active"
    static let settingsPurchaseProductUnavailable = "settings.purchase.product_unavailable"
    static let settingsPurchaseVerificationFailed = "settings.purchase.verification_failed"

    /// Google AdMob（テスト用）。本番では App Store Connect / AdMob コンソールの値に差し替える。
    static let adMobApplicationIDTest = "ca-app-pub-3940256099942544~1458002511"
    static let adMobBannerUnitIDTest = "ca-app-pub-3940256099942544/2934735716"

    static let archiveTitle = "archive.title"
    static let archiveTitleJP = "archive.title.jp"
    static let archiveTitleEN = "archive.title.en"
    static let archiveSegmentLabelTemplate = "archive.segment.label_template"

    static let libraryIndexTitle = "library.index.title"
    static let libraryCategoryTalesTitle = "library.category.tales.title"
    static let libraryCategoryTalesSubtitle = "library.category.tales.subtitle"
    static let libraryCategoryCanonsTitle = "library.category.canons.title"
    static let libraryCategoryCanonsSubtitle = "library.category.canons.subtitle"
    static let libraryCategorySeriesTitle = "library.category.series.title"
    static let libraryCategorySeriesSubtitle = "library.category.series.subtitle"
    static let libraryListSearchPrompt = "library.list.search_prompt"

    static let librarySortWikiOrder = "library.sort.wiki_order"
    static let librarySortTitleAsc = "library.sort.title_asc"
    static let librarySortTitleDesc = "library.sort.title_desc"
    static let librarySortNewest = "library.sort.newest"
    static let librarySortOldest = "library.sort.oldest"
    static let librarySortAuthorAsc = "library.sort.author_asc"
    static let librarySortAuthorHubCount = "library.sort.author_hub_count"
    static let librarySortToolbarAccessibility = "library.sort.toolbar_accessibility"

    static let goiIndexTitle = "goi.index.title"
    static let goiIndexSectionPortals = "goi.index.section.portals"
    static let goiIndexSectionEN = "goi.index.section.en"
    static let goiIndexSectionJP = "goi.index.section.jp"
    static let goiIndexPortalGoiMasterJP = "goi.index.portal.goi_master_jp"
    static let goiIndexPortalGoiFormatsEN = "goi.index.portal.goi_formats_en"
    static let goiIndexPortalInternationalFormats = "goi.index.portal.international_formats"
    static let goiIndexHubAlexylva = "goi.index.hub.alexylva"
    static let goiIndexHubAmbrose = "goi.index.hub.ambrose"
    static let goiIndexHubAnderson = "goi.index.hub.anderson"
    static let goiIndexHubArcadia = "goi.index.hub.arcadia"
    static let goiIndexHubAWCY = "goi.index.hub.awcy"
    static let goiIndexHubBlackQueen = "goi.index.hub.black_queen"
    static let goiIndexHubCI = "goi.index.hub.ci"
    static let goiIndexHubChicago = "goi.index.hub.chicago"
    static let goiIndexHubCotBG = "goi.index.hub.cotbg"
    static let goiIndexHubCotSH = "goi.index.hub.cotsh"
    static let goiIndexHubDeer = "goi.index.hub.deer"
    static let goiIndexHubFactory = "goi.index.hub.factory"
    static let goiIndexHubFifthist = "goi.index.hub.fifthist"
    static let goiIndexHubGOC = "goi.index.hub.goc"
    static let goiIndexHubGruP = "goi.index.hub.gru_p"
    static let goiIndexHubHermanFuller = "goi.index.hub.herman_fuller"
    static let goiIndexHubHI = "goi.index.hub.hi"
    static let goiIndexHubIJAMEA = "goi.index.hub.ijamea"
    static let goiIndexHubMCF = "goi.index.hub.mcf"
    static let goiIndexHubMCD = "goi.index.hub.mcd"
    static let goiIndexHubNobody = "goi.index.hub.nobody"
    static let goiIndexHubORIA = "goi.index.hub.oria"
    static let goiIndexHubOneiroi = "goi.index.hub.oneiroi"
    static let goiIndexHubParawatch = "goi.index.hub.parawatch"
    static let goiIndexHubPrometheus = "goi.index.hub.prometheus"
    static let goiIndexHubSH = "goi.index.hub.sh"
    static let goiIndexHubSPC = "goi.index.hub.spc"
    static let goiIndexHubTMI = "goi.index.hub.tmi"
    static let goiIndexHubUIU = "goi.index.hub.uiu"
    static let goiIndexHubW = "goi.index.hub.w"
    static let goiIndexHubWWS = "goi.index.hub.wws"
    static let goiIndexHubAodaisho = "goi.index.hub.aodaisho"
    static let goiIndexHubPAMWAC = "goi.index.hub.pamwac"
    static let goiIndexHubImaginanimal = "goi.index.hub.imaginanimal"
    static let goiIndexHubElma = "goi.index.hub.elma"
    static let goiIndexHubTokuzika = "goi.index.hub.tokuzika"
    static let goiIndexHubKoigarezaki = "goi.index.hub.koigarezaki"
    static let goiIndexHubSaigaha = "goi.index.hub.saigaha"
    static let goiIndexHubShushuin = "goi.index.hub.shushuin"
    static let goiIndexHubSekiryuClub = "goi.index.hub.sekiryu_club"
    static let goiIndexHubTono = "goi.index.hub.tono"
    static let goiIndexHubJOICLE = "goi.index.hub.joicle"
    static let goiIndexHubJAGPATO = "goi.index.hub.jagpato"
    static let goiIndexHubMeiteigai = "goi.index.hub.meiteigai"
    static let goiIndexHubMujinGetsudo = "goi.index.hub.mujin_getsudo"
    static let goiIndexHubYamizushi = "goi.index.hub.yamizushi"
    static let goiIndexHubYumemi = "goi.index.hub.yumemi"

    static let articleToolbarBookmark = "article.toolbar.bookmark"
    static let articleOfflineBadge = "article.offline_badge"
    static let articleLoadTimeout = "article.load.timeout"
    static let articleLoadFailed = "article.load.failed"
    static let articleLoadRetry = "article.load.retry"
    static let articleDiagnosticMinimalBanner = "article.diagnostic.minimal_banner"

    static let settingsSectionWebViewDebug = "settings.section.webview_debug"
    static let settingsWebViewMinimalToggle = "settings.webview.minimal_toggle"
    static let settingsWebViewMinimalFooter = "settings.webview.minimal_footer"
    static let settingsWebViewProbe = "settings.webview.probe"
    static let settingsWebViewProbeFooter = "settings.webview.probe_footer"
}
